#!/usr/bin/env bash
# Init script to manage manage_my_process

PIDFILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

case "$1" in
  start)
    sudo $SCRIPT &
    echo $! > $PIDFILE
    echo "manage_my_process started"
    ;;

  stop)
    if [ -f $PIDFILE ]; then
      kill $(cat $PIDFILE)
      rm -f $PIDFILE
      echo "manage_my_process stopped"
    fi
    ;;

  restart)
    if [ -f $PIDFILE ]; then
      kill $(cat $PIDFILE)
      rm -f $PIDFILE
    fi
    sudo $SCRIPT &
    echo $! > $PIDFILE
    echo "manage_my_process restarted"
    ;;

  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
